export const FETCH_LOCAL_SHIPMENT = "FETCH_LOCAL_SHIPMENT";
export const FETCH_ALL_SHIPMENT = "FETCH_ALL_SHIPMENT";
export const FILTER_SHIPMENT = "FILTER_SHIPMENT";
export const INSERT_LOCAL_SHIPMENT = "INSERT_LOCAL_SHIPMENT";
